name = "Los Pibes del Fondo 2025"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e58b712ecccb4737c8a6a52be74189735ffd6399ad0ca4cf5338ff8ad46b7bff"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
